# https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
# Problem: "I can manage all my K8s config in git, except Secrets."
apiVersion: v1
kind: Secret
metadata:
  name: node1-secret
type: Opaque
data:
  db-uri: base64 encode
