apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: cotcac/node1:latest
          resources:
            limits:
              memory: 200Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 3000
          env:
            - name: DB_URI
              value: ""
            - name: PORT
              value: "3000"  
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: test
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
